// Maps all 31 NHL teams to their abbreviation so the bot can dynamically add emotes.
const nhlmap = new Map();
nhlmap.set("ANA", "ana");
nhlmap.set("ARI", "ari");
nhlmap.set("BOS", "bos");
nhlmap.set("BUF", "buf");
nhlmap.set("CAR", "car");
nhlmap.set("CBJ", "cbj");
nhlmap.set("CGY", "cgy");
nhlmap.set("CHI", "chi");
nhlmap.set("COL", "col");
nhlmap.set("DAL", "dal");
nhlmap.set("DET", "det");
nhlmap.set("EDM", "edm");
nhlmap.set("FLA", "fla");
nhlmap.set("LAK", "lak");
nhlmap.set("MIN", "min");
nhlmap.set("MTL", "mtl");
nhlmap.set("NJD", "njd");
nhlmap.set("NSH", "nsh");
nhlmap.set("NYI", "nyi");
nhlmap.set("NYR", "nyr");
nhlmap.set("OTT", "ott");
nhlmap.set("PHI", "phi");
nhlmap.set("PIT", "pit");
nhlmap.set("SEA", "sea");
nhlmap.set("SJS", "sjs");
nhlmap.set("STL", "stl");
nhlmap.set("TBL", "tbl");
nhlmap.set("TOR", "tor");
nhlmap.set("VAN", "van");
nhlmap.set("VGK", "vgk");
nhlmap.set("WPG", "wpg");
nhlmap.set("WSH", "wsh");

module.exports = nhlmap;
